### PR TITLE
fixes to better support --force_version

### PR DESCRIPTION
**Pull request by ens-lg4**
These two fixes improve the non-interactive behaviour when --force_version is used during installation of a package.

1. If "supported_versions" AND --force_version are both given, --force_version overrides the list (as expected) and does not present the user with the list to choose from again.

2. If --force_version has already been acted upon, there is no need to re-detect the version again, as it is known.

### CODE REVIEW

**Comment by gfursin** [comment]
Thanks Leo.

I believe I understand the logic and it's fine.

One question about line
```
     force_version = i.get('force_version')
```

force_version can technically be "", right (i.e. --force_version="")?

What will happen in such case?

Maybe it's better to use the following:
```
     force_version = i.get('force_version','')
```
In such case, if force_version is None or force_version =='', it will always return '' and you can check for both cases?

**Comment by gfursin** [comment]
Thanks! Merged!

**Comment by gfursin** [comment]
@ens-lg4 .
Hi Leo,
You have recently added some new and interesting functionality to the CK packages.
Since it is now merged, do you mind to send a summary to the CK mailing list, please (a summary from the last 2 PR)?
That will be useful for the community!
Thank you very much!!!

**Comment by ens-lg4** [comment]
Thanks for merging, @gfursin !

I'm afraid the documentation may have to wait since we are currently very busy and short on people.
Sorry about it!

**Comment by gfursin** [comment]
Hi @ens-lg4 .
I didn't mean the documentation. I meant to announce PRs with the new functionality in the CK mailing list.
I have collaborators using ck-env modules - they are in the CK mailing list and will be interested to know that there is a new functionality.
So, please just send a very brief announcement with the link to 2 last PRs to the CK mailing list - that will be very useful!
Thank you very much in advance,
Grigori

**Pull request merged**
