### PR TITLE
Increase compiler.python search depth to 6

### PR DESCRIPTION
**Pull request by dsavenko**
Hi,

This PR increases compiler.python search depth to 6. Typical python installation path for Windows (if installed just for one user) is `C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32`. With depth level 4, CK was not able to find this path.

### CODE REVIEW

**Comment by gfursin** [comment]
Thanks Dima, However I have to admit that I am generally against increasing depth on Windows machines more than 4 - it then takes more then 4 minutes to search installation on my Windows machine (! - I have lots of stuff installed ;) ). 
I have a suggestion - what if instead, you update "dirs" function in a related python script - there is you detect that you are on Windows, you detect User directory and then add the following dir to search dirs:
* C:\Users\USERNAME\AppData\Local\Programs
Then you will not need to update depth and it should be quite robust and fast ...
What do you think?

**Comment by dsavenko** [comment]
Yes, I completely agree with you. Shame on me, I knew about this method, but didn't think about it :) To my defense, I needed a quick fix to continue working with Tensorflow :) 

I will update the PR soon.

**Comment by gfursin** [comment]
No worries, that's fine - there are different methods available ;) ...

**Comment by dsavenko** [comment]
@gfursin I updated the PR, please take a look. I added the standard Windows directories, where programs may install, if they don't want system-wide installation. Probably, we should add these two dirs to the global search list for the programs on Windows, as any program installed 'just for this user' most likely end up in one of these.

**Pull request merged**
