### PR TITLE
Fix Boost detection on Windows

### PR DESCRIPTION
**Pull request by dsavenko**
Hi,

This PR fixes pre-installed Boost detection on Windows.

### CODE REVIEW

**Comment by gfursin** [comment]
Thanks, @dsavenko . However, I have an issues with that on my machine. If I know compile boost via CK on Windows, the lib is not detected. I think it's because I have the following files created:
* libboost_system-mt.lib
* libboost_system-mt-gd.lib

I.e. they don't have mt-s-* in them . Will the following search name work?
     "soft_file": {
       "linux": "libboost_system.so", 
      "win": "libboost_system-*-mt*.lib"
     }, 
I.e. to be able to add "libboost_system-mt.lib"?

Thanks!

**Comment by dsavenko** [comment]
This would work, but the standard installation of Boost on Windows contains multiple files conforming to the "libboost_system-*-mt*.lib" pattern. So, it'd be detected as multiple installations. Not ideal, but if we can live with this, I'll change the code. Please, share your thoughts.

**Comment by gfursin** [comment]
I don't think that there will be multiple versions. In your and my case there will be the same 2 libs with just slightly different names. Or we can provide some extra pruning of versions if needed. But at least we will support both native lib and the one which is compiled by CK ... What do you think?

**Comment by dsavenko** [comment]
I changed the pattern as you suggested. It now picks up both compiled by CK and pre-compiled boost.

**Comment by gfursin** [comment]
Thanks!

**Comment by gfursin** [comment]
Seems to be working. Thanks!

**Pull request merged**
